// Contract check against the pinned core implementation, not a duplicated whitelist.
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..');
const bridge=fs.readFileSync(path.join(root,'entry/src/main/cpp/vpn_client.cpp'),'utf8');
const parser=fs.readFileSync(path.join(root,'entry/src/main/cpp/openvpn3/openvpn/ssl/tlsver.hpp'),'utf8');
const body=parser.slice(parser.indexOf('inline void apply_override('));
const accepted=[...body.matchAll(/override == "([^"]+)"/g)].map(m=>m[1]);
const configured=[...bridge.matchAll(/tlsVersionMinOverride\s*=\s*"([^"]+)"/g)].map(m=>m[1]);
assert(configured.length>0,'Missing minimum TLS override');
for(const value of configured)assert(accepted.includes(value),`Core rejects TLS override ${value}; accepted: ${accepted.join(', ')}`);
assert(!accepted.includes('1.2'),'The old regression fixture must be invalid in this pinned core');
assert(configured.every(x=>x==='tls_1_2'||x==='tls_1_3'),'Do not weaken TLS minimum to bypass validation');
assert(bridge.includes('TLSVersion::apply_override(minimum, c.tlsVersionMinOverride)'), 'Preflight must use the real core validator');
console.log('PASS native TLS override contract: old 1.2 rejected; configured '+configured.join(', ')+' accepted by pinned core');
const compressionParser=fs.readFileSync(path.join(root,'entry/src/main/cpp/openvpn3/openvpn/ssl/proto_context_options.hpp'),'utf8');
const compressionModes=[...compressionParser.matchAll(/mode == "([^"]+)"/g)].map(m=>m[1]);
assert(compressionModes.includes('no')&&compressionModes.includes('asym'));
assert(bridge.includes('j.get("compression", "no")'));
assert(bridge.includes('c.compressionMode != "no" && c.compressionMode != "asym"'));
assert(bridge.includes('compression.parse_compression_mode(c.compressionMode)'));
const cmake=fs.readFileSync(path.join(root,'entry/src/main/cpp/CMakeLists.txt'),'utf8');
assert(cmake.includes('HAVE_LZ4')&&cmake.includes('ovpn_lz4')&&cmake.includes('lz4/lib/lz4.c'));
assert(!cmake.includes('NO_LZO'));
const ui=fs.readFileSync(path.join(root,'entry/src/main/ets/pages/Index.ets'),'utf8');
assert(ui.includes("compression: this.receiveCompression ? 'asym' : 'no'"));
console.log('PASS compression contract: explicit receive-only selection, default disabled, LZO and LZ4 build support');
assert(bridge.includes('c.tunPersist = false'), 'Do not retain core-owned old descriptor across system TUN recreation');
const tunClient=fs.readFileSync(path.join(root,'entry/src/main/cpp/openvpn3/openvpn/tun/builder/client.hpp'),'utf8');
assert(tunClient.includes('tun_persist.reset();'));
console.log('PASS core persistence disabled; ability owns system TUN reuse');
